// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package order

import (
	"context"
	"fmt"
	"full_backend_practice/kitex_gen/base"
)

type SeckillReq struct {
	UserId    int64 `thrift:"user_id,1,required" frugal:"1,required,i64" json:"user_id"`
	ProductId int64 `thrift:"product_id,2,required" frugal:"2,required,i64" json:"product_id"`
}

func NewSeckillReq() *SeckillReq {
	return &SeckillReq{}
}

func (p *SeckillReq) InitDefault() {
}

func (p *SeckillReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *SeckillReq) GetProductId() (v int64) {
	return p.ProductId
}
func (p *SeckillReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *SeckillReq) SetProductId(val int64) {
	p.ProductId = val
}

func (p *SeckillReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SeckillReq(%+v)", *p)
}

var fieldIDToName_SeckillReq = map[int16]string{
	1: "user_id",
	2: "product_id",
}

type SeckillResp struct {
	BaseResp *base.BaseResp `thrift:"base_resp,1,required" frugal:"1,required,base.BaseResp" json:"base_resp"`
	OrderNo  *string        `thrift:"order_no,2,optional" frugal:"2,optional,string" json:"order_no,omitempty"`
}

func NewSeckillResp() *SeckillResp {
	return &SeckillResp{}
}

func (p *SeckillResp) InitDefault() {
}

var SeckillResp_BaseResp_DEFAULT *base.BaseResp

func (p *SeckillResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return SeckillResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var SeckillResp_OrderNo_DEFAULT string

func (p *SeckillResp) GetOrderNo() (v string) {
	if !p.IsSetOrderNo() {
		return SeckillResp_OrderNo_DEFAULT
	}
	return *p.OrderNo
}
func (p *SeckillResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}
func (p *SeckillResp) SetOrderNo(val *string) {
	p.OrderNo = val
}

func (p *SeckillResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *SeckillResp) IsSetOrderNo() bool {
	return p.OrderNo != nil
}

func (p *SeckillResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SeckillResp(%+v)", *p)
}

var fieldIDToName_SeckillResp = map[int16]string{
	1: "base_resp",
	2: "order_no",
}

type OrderService interface {
	Seckill(ctx context.Context, req *SeckillReq) (r *SeckillResp, err error)
}

type OrderServiceSeckillArgs struct {
	Req *SeckillReq `thrift:"req,1" frugal:"1,default,SeckillReq" json:"req"`
}

func NewOrderServiceSeckillArgs() *OrderServiceSeckillArgs {
	return &OrderServiceSeckillArgs{}
}

func (p *OrderServiceSeckillArgs) InitDefault() {
}

var OrderServiceSeckillArgs_Req_DEFAULT *SeckillReq

func (p *OrderServiceSeckillArgs) GetReq() (v *SeckillReq) {
	if !p.IsSetReq() {
		return OrderServiceSeckillArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceSeckillArgs) SetReq(val *SeckillReq) {
	p.Req = val
}

func (p *OrderServiceSeckillArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceSeckillArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceSeckillArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceSeckillArgs = map[int16]string{
	1: "req",
}

type OrderServiceSeckillResult struct {
	Success *SeckillResp `thrift:"success,0,optional" frugal:"0,optional,SeckillResp" json:"success,omitempty"`
}

func NewOrderServiceSeckillResult() *OrderServiceSeckillResult {
	return &OrderServiceSeckillResult{}
}

func (p *OrderServiceSeckillResult) InitDefault() {
}

var OrderServiceSeckillResult_Success_DEFAULT *SeckillResp

func (p *OrderServiceSeckillResult) GetSuccess() (v *SeckillResp) {
	if !p.IsSetSuccess() {
		return OrderServiceSeckillResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceSeckillResult) SetSuccess(x interface{}) {
	p.Success = x.(*SeckillResp)
}

func (p *OrderServiceSeckillResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceSeckillResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceSeckillResult(%+v)", *p)
}

var fieldIDToName_OrderServiceSeckillResult = map[int16]string{
	0: "success",
}
