mysql:
  dsn: "root:root@tcp(127.0.0.1:13306)/seckill_db?charset=utf8mb4&parseTime=True&loc=Local"
redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0
rabbitmq:
  url: "amqp://guest:guest@127.0.0.1:5672/"
  queues:
    - "order_seckill"
    - "product_list"
    - "product_single"
etcd:
  endpoints:
    - "127.0.0.1:2379"
server:
  api_gateway_port: "8081"
  user_rpc_port: "8889"
  product_rpc_port: "8890"
  order_rpc_port: "8891"

tracer:
  enabled: true
  endpoint: localhost:14317
