// Code generated by Kitex v0.16.1. DO NOT EDIT.

package productservice

import (
	"context"
	"errors"
	product "full_backend_practice/kitex_gen/product"

	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetProductList": kitex.NewMethodInfo(
		getProductListHandler,
		newProductServiceGetProductListArgs,
		newProductServiceGetProductListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetProduct": kitex.NewMethodInfo(
		getProductHandler,
		newProductServiceGetProductArgs,
		newProductServiceGetProductResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateProduct": kitex.NewMethodInfo(
		createProductHandler,
		newProductServiceCreateProductArgs,
		newProductServiceCreateProductResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"HeatProduct": kitex.NewMethodInfo(
		heatProductHandler,
		newProductServiceHeatProductArgs,
		newProductServiceHeatProductResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	productServiceServiceInfo                = NewServiceInfo()
	productServiceServiceInfoForClient       = NewServiceInfoForClient()
	productServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return productServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return productServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return productServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ProductService"
	handlerType := (*product.ProductService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "product",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func getProductListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*product.ProductServiceGetProductListArgs)
	realResult := result.(*product.ProductServiceGetProductListResult)
	success, err := handler.(product.ProductService).GetProductList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProductServiceGetProductListArgs() interface{} {
	return product.NewProductServiceGetProductListArgs()
}

func newProductServiceGetProductListResult() interface{} {
	return product.NewProductServiceGetProductListResult()
}

func getProductHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*product.ProductServiceGetProductArgs)
	realResult := result.(*product.ProductServiceGetProductResult)
	success, err := handler.(product.ProductService).GetProduct(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProductServiceGetProductArgs() interface{} {
	return product.NewProductServiceGetProductArgs()
}

func newProductServiceGetProductResult() interface{} {
	return product.NewProductServiceGetProductResult()
}

func createProductHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*product.ProductServiceCreateProductArgs)
	realResult := result.(*product.ProductServiceCreateProductResult)
	success, err := handler.(product.ProductService).CreateProduct(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProductServiceCreateProductArgs() interface{} {
	return product.NewProductServiceCreateProductArgs()
}

func newProductServiceCreateProductResult() interface{} {
	return product.NewProductServiceCreateProductResult()
}

func heatProductHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*product.ProductServiceHeatProductArgs)
	realResult := result.(*product.ProductServiceHeatProductResult)
	success, err := handler.(product.ProductService).HeatProduct(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProductServiceHeatProductArgs() interface{} {
	return product.NewProductServiceHeatProductArgs()
}

func newProductServiceHeatProductResult() interface{} {
	return product.NewProductServiceHeatProductResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetProductList(ctx context.Context, req *product.GetProductListReq) (r *product.GetProductListResp, err error) {
	var _args product.ProductServiceGetProductListArgs
	_args.Req = req
	var _result product.ProductServiceGetProductListResult
	if err = p.c.Call(ctx, "GetProductList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetProduct(ctx context.Context, req *product.GetProductReq) (r *product.GetProductResp, err error) {
	var _args product.ProductServiceGetProductArgs
	_args.Req = req
	var _result product.ProductServiceGetProductResult
	if err = p.c.Call(ctx, "GetProduct", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateProduct(ctx context.Context, req *product.CreateProductReq) (r *product.CreateProductResp, err error) {
	var _args product.ProductServiceCreateProductArgs
	_args.Req = req
	var _result product.ProductServiceCreateProductResult
	if err = p.c.Call(ctx, "CreateProduct", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) HeatProduct(ctx context.Context, req *product.HeatProductReq) (r *product.HeatProductResp, err error) {
	var _args product.ProductServiceHeatProductArgs
	_args.Req = req
	var _result product.ProductServiceHeatProductResult
	if err = p.c.Call(ctx, "HeatProduct", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
