// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package product

import (
	"context"
	"fmt"
	"full_backend_practice/kitex_gen/base"
)

type ProductInfo struct {
	Id    int64   `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Name  string  `thrift:"name,2" frugal:"2,default,string" json:"name"`
	Price float64 `thrift:"price,3" frugal:"3,default,double" json:"price"`
	Stock int32   `thrift:"stock,4" frugal:"4,default,i32" json:"stock"`
}

func NewProductInfo() *ProductInfo {
	return &ProductInfo{}
}

func (p *ProductInfo) InitDefault() {
}

func (p *ProductInfo) GetId() (v int64) {
	return p.Id
}

func (p *ProductInfo) GetName() (v string) {
	return p.Name
}

func (p *ProductInfo) GetPrice() (v float64) {
	return p.Price
}

func (p *ProductInfo) GetStock() (v int32) {
	return p.Stock
}
func (p *ProductInfo) SetId(val int64) {
	p.Id = val
}
func (p *ProductInfo) SetName(val string) {
	p.Name = val
}
func (p *ProductInfo) SetPrice(val float64) {
	p.Price = val
}
func (p *ProductInfo) SetStock(val int32) {
	p.Stock = val
}

func (p *ProductInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductInfo(%+v)", *p)
}

var fieldIDToName_ProductInfo = map[int16]string{
	1: "id",
	2: "name",
	3: "price",
	4: "stock",
}

type GetProductReq struct {
	ProductId int64 `thrift:"product_id,1,required" frugal:"1,required,i64" json:"product_id"`
}

func NewGetProductReq() *GetProductReq {
	return &GetProductReq{}
}

func (p *GetProductReq) InitDefault() {
}

func (p *GetProductReq) GetProductId() (v int64) {
	return p.ProductId
}
func (p *GetProductReq) SetProductId(val int64) {
	p.ProductId = val
}

func (p *GetProductReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetProductReq(%+v)", *p)
}

var fieldIDToName_GetProductReq = map[int16]string{
	1: "product_id",
}

type GetProductResp struct {
	BaseResp *base.BaseResp `thrift:"base_resp,1,required" frugal:"1,required,base.BaseResp" json:"base_resp"`
	Product  *ProductInfo   `thrift:"product,2,optional" frugal:"2,optional,ProductInfo" json:"product,omitempty"`
}

func NewGetProductResp() *GetProductResp {
	return &GetProductResp{}
}

func (p *GetProductResp) InitDefault() {
}

var GetProductResp_BaseResp_DEFAULT *base.BaseResp

func (p *GetProductResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetProductResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var GetProductResp_Product_DEFAULT *ProductInfo

func (p *GetProductResp) GetProduct() (v *ProductInfo) {
	if !p.IsSetProduct() {
		return GetProductResp_Product_DEFAULT
	}
	return p.Product
}
func (p *GetProductResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}
func (p *GetProductResp) SetProduct(val *ProductInfo) {
	p.Product = val
}

func (p *GetProductResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetProductResp) IsSetProduct() bool {
	return p.Product != nil
}

func (p *GetProductResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetProductResp(%+v)", *p)
}

var fieldIDToName_GetProductResp = map[int16]string{
	1: "base_resp",
	2: "product",
}

type ProductService interface {
	GetProduct(ctx context.Context, req *GetProductReq) (r *GetProductResp, err error)
}

type ProductServiceGetProductArgs struct {
	Req *GetProductReq `thrift:"req,1" frugal:"1,default,GetProductReq" json:"req"`
}

func NewProductServiceGetProductArgs() *ProductServiceGetProductArgs {
	return &ProductServiceGetProductArgs{}
}

func (p *ProductServiceGetProductArgs) InitDefault() {
}

var ProductServiceGetProductArgs_Req_DEFAULT *GetProductReq

func (p *ProductServiceGetProductArgs) GetReq() (v *GetProductReq) {
	if !p.IsSetReq() {
		return ProductServiceGetProductArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ProductServiceGetProductArgs) SetReq(val *GetProductReq) {
	p.Req = val
}

func (p *ProductServiceGetProductArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ProductServiceGetProductArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceGetProductArgs(%+v)", *p)
}

var fieldIDToName_ProductServiceGetProductArgs = map[int16]string{
	1: "req",
}

type ProductServiceGetProductResult struct {
	Success *GetProductResp `thrift:"success,0,optional" frugal:"0,optional,GetProductResp" json:"success,omitempty"`
}

func NewProductServiceGetProductResult() *ProductServiceGetProductResult {
	return &ProductServiceGetProductResult{}
}

func (p *ProductServiceGetProductResult) InitDefault() {
}

var ProductServiceGetProductResult_Success_DEFAULT *GetProductResp

func (p *ProductServiceGetProductResult) GetSuccess() (v *GetProductResp) {
	if !p.IsSetSuccess() {
		return ProductServiceGetProductResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProductServiceGetProductResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetProductResp)
}

func (p *ProductServiceGetProductResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProductServiceGetProductResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceGetProductResult(%+v)", *p)
}

var fieldIDToName_ProductServiceGetProductResult = map[int16]string{
	0: "success",
}
