// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package product

import (
	"context"
	"fmt"
	"full_backend_practice/kitex_gen/base"
)

type ProductInfo struct {
	Id           int64   `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Name         string  `thrift:"name,2" frugal:"2,default,string" json:"name"`
	Price        float64 `thrift:"price,3" frugal:"3,default,double" json:"price"`
	SeckillPrict float64 `thrift:"seckill_prict,5" frugal:"5,default,double" json:"seckill_prict"`
	Stock        int32   `thrift:"stock,6" frugal:"6,default,i32" json:"stock"`
	Version      int32   `thrift:"version,7" frugal:"7,default,i32" json:"version"`
	StartTime    string  `thrift:"start_time,8" frugal:"8,default,string" json:"start_time"`
	EndTime      string  `thrift:"end_time,9" frugal:"9,default,string" json:"end_time"`
}

func NewProductInfo() *ProductInfo {
	return &ProductInfo{}
}

func (p *ProductInfo) InitDefault() {
}

func (p *ProductInfo) GetId() (v int64) {
	return p.Id
}

func (p *ProductInfo) GetName() (v string) {
	return p.Name
}

func (p *ProductInfo) GetPrice() (v float64) {
	return p.Price
}

func (p *ProductInfo) GetSeckillPrict() (v float64) {
	return p.SeckillPrict
}

func (p *ProductInfo) GetStock() (v int32) {
	return p.Stock
}

func (p *ProductInfo) GetVersion() (v int32) {
	return p.Version
}

func (p *ProductInfo) GetStartTime() (v string) {
	return p.StartTime
}

func (p *ProductInfo) GetEndTime() (v string) {
	return p.EndTime
}
func (p *ProductInfo) SetId(val int64) {
	p.Id = val
}
func (p *ProductInfo) SetName(val string) {
	p.Name = val
}
func (p *ProductInfo) SetPrice(val float64) {
	p.Price = val
}
func (p *ProductInfo) SetSeckillPrict(val float64) {
	p.SeckillPrict = val
}
func (p *ProductInfo) SetStock(val int32) {
	p.Stock = val
}
func (p *ProductInfo) SetVersion(val int32) {
	p.Version = val
}
func (p *ProductInfo) SetStartTime(val string) {
	p.StartTime = val
}
func (p *ProductInfo) SetEndTime(val string) {
	p.EndTime = val
}

func (p *ProductInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductInfo(%+v)", *p)
}

var fieldIDToName_ProductInfo = map[int16]string{
	1: "id",
	2: "name",
	3: "price",
	5: "seckill_prict",
	6: "stock",
	7: "version",
	8: "start_time",
	9: "end_time",
}

type GetProductListReq struct {
}

func NewGetProductListReq() *GetProductListReq {
	return &GetProductListReq{}
}

func (p *GetProductListReq) InitDefault() {
}

func (p *GetProductListReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetProductListReq(%+v)", *p)
}

var fieldIDToName_GetProductListReq = map[int16]string{}

type GetProductListResp struct {
	BaseResp *base.BaseResp `thrift:"base_resp,1,required" frugal:"1,required,base.BaseResp" json:"base_resp"`
	Products []*ProductInfo `thrift:"products,2" frugal:"2,default,list<ProductInfo>" json:"products"`
}

func NewGetProductListResp() *GetProductListResp {
	return &GetProductListResp{}
}

func (p *GetProductListResp) InitDefault() {
}

var GetProductListResp_BaseResp_DEFAULT *base.BaseResp

func (p *GetProductListResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetProductListResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *GetProductListResp) GetProducts() (v []*ProductInfo) {
	return p.Products
}
func (p *GetProductListResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}
func (p *GetProductListResp) SetProducts(val []*ProductInfo) {
	p.Products = val
}

func (p *GetProductListResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetProductListResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetProductListResp(%+v)", *p)
}

var fieldIDToName_GetProductListResp = map[int16]string{
	1: "base_resp",
	2: "products",
}

type GetProductReq struct {
	ProductId int64 `thrift:"product_id,1,required" frugal:"1,required,i64" json:"product_id"`
}

func NewGetProductReq() *GetProductReq {
	return &GetProductReq{}
}

func (p *GetProductReq) InitDefault() {
}

func (p *GetProductReq) GetProductId() (v int64) {
	return p.ProductId
}
func (p *GetProductReq) SetProductId(val int64) {
	p.ProductId = val
}

func (p *GetProductReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetProductReq(%+v)", *p)
}

var fieldIDToName_GetProductReq = map[int16]string{
	1: "product_id",
}

type GetProductResp struct {
	BaseResp *base.BaseResp `thrift:"base_resp,1,required" frugal:"1,required,base.BaseResp" json:"base_resp"`
	Product  *ProductInfo   `thrift:"product,2,optional" frugal:"2,optional,ProductInfo" json:"product,omitempty"`
}

func NewGetProductResp() *GetProductResp {
	return &GetProductResp{}
}

func (p *GetProductResp) InitDefault() {
}

var GetProductResp_BaseResp_DEFAULT *base.BaseResp

func (p *GetProductResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetProductResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var GetProductResp_Product_DEFAULT *ProductInfo

func (p *GetProductResp) GetProduct() (v *ProductInfo) {
	if !p.IsSetProduct() {
		return GetProductResp_Product_DEFAULT
	}
	return p.Product
}
func (p *GetProductResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}
func (p *GetProductResp) SetProduct(val *ProductInfo) {
	p.Product = val
}

func (p *GetProductResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetProductResp) IsSetProduct() bool {
	return p.Product != nil
}

func (p *GetProductResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetProductResp(%+v)", *p)
}

var fieldIDToName_GetProductResp = map[int16]string{
	1: "base_resp",
	2: "product",
}

type CreateProductReq struct {
	Name         string  `thrift:"name,1,required" frugal:"1,required,string" json:"name"`
	Price        float64 `thrift:"price,2,required" frugal:"2,required,double" json:"price"`
	SeckillPrict float64 `thrift:"seckill_prict,3,required" frugal:"3,required,double" json:"seckill_prict"`
	Stock        int32   `thrift:"stock,4,required" frugal:"4,required,i32" json:"stock"`
	Version      int32   `thrift:"version,5,required" frugal:"5,required,i32" json:"version"`
	StartTime    int64   `thrift:"start_time,6,required" frugal:"6,required,i64" json:"start_time"`
	EndTime      int64   `thrift:"end_time,7,required" frugal:"7,required,i64" json:"end_time"`
}

func NewCreateProductReq() *CreateProductReq {
	return &CreateProductReq{}
}

func (p *CreateProductReq) InitDefault() {
}

func (p *CreateProductReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateProductReq(%+v)", *p)
}

var fieldIDToName_CreateProductReq = map[int16]string{
	1: "name",
	2: "price",
	3: "seckill_prict",
	4: "stock",
	5: "version",
	6: "start_time",
	7: "end_time",
}

type CreateProductResp struct {
	BaseResp *base.BaseResp `thrift:"base_resp,1,required" frugal:"1,required,base.BaseResp" json:"base_resp"`
	Product  *ProductInfo   `thrift:"product,2,optional" frugal:"2,optional,ProductInfo" json:"product,omitempty"`
}

func NewCreateProductResp() *CreateProductResp {
	return &CreateProductResp{}
}

func (p *CreateProductResp) InitDefault() {
}

var CreateProductResp_BaseResp_DEFAULT *base.BaseResp

func (p *CreateProductResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return CreateProductResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var CreateProductResp_Product_DEFAULT *ProductInfo

func (p *CreateProductResp) GetProduct() (v *ProductInfo) {
	if !p.IsSetProduct() {
		return CreateProductResp_Product_DEFAULT
	}
	return p.Product
}
func (p *CreateProductResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}
func (p *CreateProductResp) SetProduct(val *ProductInfo) {
	p.Product = val
}

func (p *CreateProductResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CreateProductResp) IsSetProduct() bool {
	return p.Product != nil
}

func (p *CreateProductResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateProductResp(%+v)", *p)
}

var fieldIDToName_CreateProductResp = map[int16]string{
	1: "base_resp",
	2: "product",
}

type HeatProductReq struct {
}

func NewHeatProductReq() *HeatProductReq {
	return &HeatProductReq{}
}

func (p *HeatProductReq) InitDefault() {
}

func (p *HeatProductReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HeatProductReq(%+v)", *p)
}

var fieldIDToName_HeatProductReq = map[int16]string{}

type HeatProductResp struct {
	BaseResp *base.BaseResp `thrift:"base_resp,1,required" frugal:"1,required,base.BaseResp" json:"base_resp"`
}

func NewHeatProductResp() *HeatProductResp {
	return &HeatProductResp{}
}

func (p *HeatProductResp) InitDefault() {
}

var HeatProductResp_BaseResp_DEFAULT *base.BaseResp

func (p *HeatProductResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return HeatProductResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *HeatProductResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *HeatProductResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *HeatProductResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HeatProductResp(%+v)", *p)
}

var fieldIDToName_HeatProductResp = map[int16]string{
	1: "base_resp",
}

type ProductService interface {
	GetProductList(ctx context.Context, req *GetProductListReq) (r *GetProductListResp, err error)

	GetProduct(ctx context.Context, req *GetProductReq) (r *GetProductResp, err error)

	CreateProduct(ctx context.Context, req *CreateProductReq) (r *CreateProductResp, err error)

	HeatProduct(ctx context.Context, req *HeatProductReq) (r *HeatProductResp, err error)
}

type ProductServiceGetProductListArgs struct {
	Req *GetProductListReq `thrift:"req,1" frugal:"1,default,GetProductListReq" json:"req"`
}

func NewProductServiceGetProductListArgs() *ProductServiceGetProductListArgs {
	return &ProductServiceGetProductListArgs{}
}

func (p *ProductServiceGetProductListArgs) InitDefault() {
}

var ProductServiceGetProductListArgs_Req_DEFAULT *GetProductListReq

func (p *ProductServiceGetProductListArgs) GetReq() (v *GetProductListReq) {
	if !p.IsSetReq() {
		return ProductServiceGetProductListArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ProductServiceGetProductListArgs) SetReq(val *GetProductListReq) {
	p.Req = val
}

func (p *ProductServiceGetProductListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ProductServiceGetProductListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceGetProductListArgs(%+v)", *p)
}

var fieldIDToName_ProductServiceGetProductListArgs = map[int16]string{
	1: "req",
}

type ProductServiceGetProductListResult struct {
	Success *GetProductListResp `thrift:"success,0,optional" frugal:"0,optional,GetProductListResp" json:"success,omitempty"`
}

func NewProductServiceGetProductListResult() *ProductServiceGetProductListResult {
	return &ProductServiceGetProductListResult{}
}

func (p *ProductServiceGetProductListResult) InitDefault() {
}

var ProductServiceGetProductListResult_Success_DEFAULT *GetProductListResp

func (p *ProductServiceGetProductListResult) GetSuccess() (v *GetProductListResp) {
	if !p.IsSetSuccess() {
		return ProductServiceGetProductListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProductServiceGetProductListResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetProductListResp)
}

func (p *ProductServiceGetProductListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProductServiceGetProductListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceGetProductListResult(%+v)", *p)
}

var fieldIDToName_ProductServiceGetProductListResult = map[int16]string{
	0: "success",
}

type ProductServiceGetProductArgs struct {
	Req *GetProductReq `thrift:"req,1" frugal:"1,default,GetProductReq" json:"req"`
}

func NewProductServiceGetProductArgs() *ProductServiceGetProductArgs {
	return &ProductServiceGetProductArgs{}
}

func (p *ProductServiceGetProductArgs) InitDefault() {
}

var ProductServiceGetProductArgs_Req_DEFAULT *GetProductReq

func (p *ProductServiceGetProductArgs) GetReq() (v *GetProductReq) {
	if !p.IsSetReq() {
		return ProductServiceGetProductArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ProductServiceGetProductArgs) SetReq(val *GetProductReq) {
	p.Req = val
}

func (p *ProductServiceGetProductArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ProductServiceGetProductArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceGetProductArgs(%+v)", *p)
}

var fieldIDToName_ProductServiceGetProductArgs = map[int16]string{
	1: "req",
}

type ProductServiceGetProductResult struct {
	Success *GetProductResp `thrift:"success,0,optional" frugal:"0,optional,GetProductResp" json:"success,omitempty"`
}

func NewProductServiceGetProductResult() *ProductServiceGetProductResult {
	return &ProductServiceGetProductResult{}
}

func (p *ProductServiceGetProductResult) InitDefault() {
}

var ProductServiceGetProductResult_Success_DEFAULT *GetProductResp

func (p *ProductServiceGetProductResult) GetSuccess() (v *GetProductResp) {
	if !p.IsSetSuccess() {
		return ProductServiceGetProductResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProductServiceGetProductResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetProductResp)
}

func (p *ProductServiceGetProductResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProductServiceGetProductResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceGetProductResult(%+v)", *p)
}

var fieldIDToName_ProductServiceGetProductResult = map[int16]string{
	0: "success",
}

type ProductServiceCreateProductArgs struct {
	Req *CreateProductReq `thrift:"req,1" frugal:"1,default,CreateProductReq" json:"req"`
}

func NewProductServiceCreateProductArgs() *ProductServiceCreateProductArgs {
	return &ProductServiceCreateProductArgs{}
}

func (p *ProductServiceCreateProductArgs) InitDefault() {
}

var ProductServiceCreateProductArgs_Req_DEFAULT *CreateProductReq

func (p *ProductServiceCreateProductArgs) GetReq() (v *CreateProductReq) {
	if !p.IsSetReq() {
		return ProductServiceCreateProductArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ProductServiceCreateProductArgs) SetReq(val *CreateProductReq) {
	p.Req = val
}

func (p *ProductServiceCreateProductArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ProductServiceCreateProductArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceCreateProductArgs(%+v)", *p)
}

var fieldIDToName_ProductServiceCreateProductArgs = map[int16]string{
	1: "req",
}

type ProductServiceCreateProductResult struct {
	Success *CreateProductResp `thrift:"success,0,optional" frugal:"0,optional,CreateProductResp" json:"success,omitempty"`
}

func NewProductServiceCreateProductResult() *ProductServiceCreateProductResult {
	return &ProductServiceCreateProductResult{}
}

func (p *ProductServiceCreateProductResult) InitDefault() {
}

var ProductServiceCreateProductResult_Success_DEFAULT *CreateProductResp

func (p *ProductServiceCreateProductResult) GetSuccess() (v *CreateProductResp) {
	if !p.IsSetSuccess() {
		return ProductServiceCreateProductResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProductServiceCreateProductResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateProductResp)
}

func (p *ProductServiceCreateProductResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProductServiceCreateProductResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceCreateProductResult(%+v)", *p)
}

var fieldIDToName_ProductServiceCreateProductResult = map[int16]string{
	0: "success",
}

type ProductServiceHeatProductArgs struct {
	Req *HeatProductReq `thrift:"req,1" frugal:"1,default,HeatProductReq" json:"req"`
}

func NewProductServiceHeatProductArgs() *ProductServiceHeatProductArgs {
	return &ProductServiceHeatProductArgs{}
}

func (p *ProductServiceHeatProductArgs) InitDefault() {
}

var ProductServiceHeatProductArgs_Req_DEFAULT *HeatProductReq

func (p *ProductServiceHeatProductArgs) GetReq() (v *HeatProductReq) {
	if !p.IsSetReq() {
		return ProductServiceHeatProductArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ProductServiceHeatProductArgs) SetReq(val *HeatProductReq) {
	p.Req = val
}

func (p *ProductServiceHeatProductArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ProductServiceHeatProductArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceHeatProductArgs(%+v)", *p)
}

var fieldIDToName_ProductServiceHeatProductArgs = map[int16]string{
	1: "req",
}

type ProductServiceHeatProductResult struct {
	Success *HeatProductResp `thrift:"success,0,optional" frugal:"0,optional,HeatProductResp" json:"success,omitempty"`
}

func NewProductServiceHeatProductResult() *ProductServiceHeatProductResult {
	return &ProductServiceHeatProductResult{}
}

func (p *ProductServiceHeatProductResult) InitDefault() {
}

var ProductServiceHeatProductResult_Success_DEFAULT *HeatProductResp

func (p *ProductServiceHeatProductResult) GetSuccess() (v *HeatProductResp) {
	if !p.IsSetSuccess() {
		return ProductServiceHeatProductResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProductServiceHeatProductResult) SetSuccess(x interface{}) {
	p.Success = x.(*HeatProductResp)
}

func (p *ProductServiceHeatProductResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProductServiceHeatProductResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceHeatProductResult(%+v)", *p)
}

var fieldIDToName_ProductServiceHeatProductResult = map[int16]string{
	0: "success",
}
