// Code generated by Kitex v0.16.1. DO NOT EDIT.

package orderservice

import (
	"context"
	"errors"
	order "full_backend_practice/kitex_gen/order"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Seckill": kitex.NewMethodInfo(
		seckillHandler,
		newOrderServiceSeckillArgs,
		newOrderServiceSeckillResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetSeckillPath": kitex.NewMethodInfo(
		getSeckillPathHandler,
		newOrderServiceGetSeckillPathArgs,
		newOrderServiceGetSeckillPathResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetSeckillResult": kitex.NewMethodInfo(
		getSeckillResult_Handler,
		newOrderServiceGetSeckillResultArgs,
		newOrderServiceGetSeckillResultResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	orderServiceServiceInfo                = NewServiceInfo()
	orderServiceServiceInfoForClient       = NewServiceInfoForClient()
	orderServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return orderServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return orderServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return orderServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "OrderService"
	handlerType := (*order.OrderService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "order",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func seckillHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*order.OrderServiceSeckillArgs)
	realResult := result.(*order.OrderServiceSeckillResult)
	success, err := handler.(order.OrderService).Seckill(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceSeckillArgs() interface{} {
	return order.NewOrderServiceSeckillArgs()
}

func newOrderServiceSeckillResult() interface{} {
	return order.NewOrderServiceSeckillResult()
}

func getSeckillPathHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*order.OrderServiceGetSeckillPathArgs)
	realResult := result.(*order.OrderServiceGetSeckillPathResult)
	success, err := handler.(order.OrderService).GetSeckillPath(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceGetSeckillPathArgs() interface{} {
	return order.NewOrderServiceGetSeckillPathArgs()
}

func newOrderServiceGetSeckillPathResult() interface{} {
	return order.NewOrderServiceGetSeckillPathResult()
}

func getSeckillResult_Handler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*order.OrderServiceGetSeckillResultArgs)
	realResult := result.(*order.OrderServiceGetSeckillResultResult)
	success, err := handler.(order.OrderService).GetSeckillResult_(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceGetSeckillResultArgs() interface{} {
	return order.NewOrderServiceGetSeckillResultArgs()
}

func newOrderServiceGetSeckillResultResult() interface{} {
	return order.NewOrderServiceGetSeckillResultResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Seckill(ctx context.Context, req *order.SeckillReq) (r *order.SeckillResp, err error) {
	var _args order.OrderServiceSeckillArgs
	_args.Req = req
	var _result order.OrderServiceSeckillResult
	if err = p.c.Call(ctx, "Seckill", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetSeckillPath(ctx context.Context, req *order.GetSeckillPathReq) (r *order.GetSeckillPathResp, err error) {
	var _args order.OrderServiceGetSeckillPathArgs
	_args.Req = req
	var _result order.OrderServiceGetSeckillPathResult
	if err = p.c.Call(ctx, "GetSeckillPath", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetSeckillResult_(ctx context.Context, req *order.GetSeckillResultReq) (r *order.GetSeckillResultResp, err error) {
	var _args order.OrderServiceGetSeckillResultArgs
	_args.Req = req
	var _result order.OrderServiceGetSeckillResultResult
	if err = p.c.Call(ctx, "GetSeckillResult", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
